django_website_project/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('school_website_template.urls', namespace='main')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school_website_template/urls.py
from django.conf.urls import url
from .views import MainPageView, GalleryView, AllGalleriesView, UploadView, WebsitePostCreate, ContactView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^main', MainPageView.as_view(), name="main_page"),
    url(r'^gallery/all', AllGalleriesView.as_view(), name="gallery_view"),
    url(r'^gallery/(?P<pk>\d+)/', GalleryView.as_view(), name="gallery_view"),
    url(r'^gallery/upload', UploadView.as_view(), name='upload_view'),
    url(r'^addPost', WebsitePostCreate.as_view(), name='create_post'),
    url(r'^contact', ContactView.as_view(),name="contact"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school_website_template/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from .models_properties.website_post_properties import CATEGORIES


class WebsitePost(models.Model):
    content = RichTextUploadingField()
    date = models.DateField(auto_now_add=True, blank=True)
    author = models.CharField(max_length=150, blank=True)
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=120, choices=CATEGORIES)

    image = models.ImageField(blank=True)

    class Meta:
        verbose_name = 'wpis'
        verbose_name_plural = 'Wpisy'


class Gallery(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'galeria'
        verbose_name_plural = "Galerie"


class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='image_in_gallery')
    image = models.ImageField(upload_to='gallery/%Y/%m/%d')
    title = models.CharField(max_length=200, null=True)

    def __str__(self):
        return 'blabla'

    class Meta:
        verbose_name = 'zdjęcie'
        verbose_name_plural = "Zdjęcia"

school_website_template/forms.py
from __future__ import absolute_import
from django import forms
from multiupload.fields import MultiImageField
from .models import Gallery, GalleryImage, WebsitePost
from ckeditor.fields import RichTextFormField


class UploadForm(forms.ModelForm):

    class Meta:
        model = Gallery
        fields = ['title', 'author']

    images = MultiImageField(min_num=1, max_num=500, max_file_size=1024*1024*5)

    def save(self, commit=True):
        instance = super(UploadForm, self).save(commit)
        for each in self.cleaned_data['images']:
            GalleryImage.objects.create(image=each, gallery=instance)
        return instance


class WebsitePostForm(forms.ModelForm):

    class Meta:
        model = WebsitePost
        fields = ['content', 'author', 'title', 'category', 'image']

school_website_template/views.py
from django.views.generic.list import ListView
from .models import WebsitePost, Gallery
from django.views.generic.edit import CreateView
from .forms import UploadForm, WebsitePostForm
from django.template.defaulttags import register
from .configuration import Link


# when we create some views we should add whole configuration into

class MainPageView(ListView):
    model = WebsitePost
    template_name = 'main_page/main_page.html'

    link = Link()

    def get_context_data(self, *args, **kwargs):
        context = super(MainPageView, self).get_context_data(*args, **kwargs)
        context['link'] = self.link
        context['list_of_website_posts'] = WebsitePost.objects.all()[:2]
        return context


class GalleryView(ListView):
    model = Gallery
    template_name = 'gallery/all_of_current_id.html'
    context_object_name = 'list_of_images'

    link = Link()

    def get_context_data(self, *args, **kwargs):
        gallery = Gallery.objects.filter(pk=self.kwargs['pk']).get()
        image_list = gallery.image_in_gallery.all()
        context = super(GalleryView, self).get_context_data(*args, **kwargs)

        context['link'] = self.link
        context['list_of_images'] = image_list
        return context

    def key(d, key_name):
        return d[key_name]

    key = register.filter('key', key)


class AllGalleriesView(ListView):
    model = Gallery
    template_name = 'gallery/all_galleries.html'

    link = Link()

    def get_context_data(self, *args, **kwargs):
        context = super(AllGalleriesView, self).get_context_data(*args, **kwargs)
        context['link'] = self.link
        context['list_of_images'] = Gallery.objects.all()
        return context


class UploadView(CreateView):
    model = Gallery
    form_class = UploadForm
    template_name = 'gallery/upload.html'
    success_url = '/all'


class WebsitePostCreate(CreateView):
    model = WebsitePost
    form_class = WebsitePostForm
    template_name = 'website_post/create_website_post.html'
    success_url = '/main'


class ContactView(ListView):
    model = WebsitePost
    template_name = 'contact.html'
    link = Link()

    def get_context_data(self, *args, **kwargs):
        context = super(ContactView, self).get_context_data(*args, **kwargs)
        context['link'] = self.link
        return context

school_website_template/templates/base.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <title>Strona główna</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static from staticfiles %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/css?family=Sahitya" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

        <script src="http://code.jquery.com/jquery-latest.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

        <style>
            .img-post {
                margin-right: 10px;
                margin-bottom: 10px;
                max-width: 480px;
            }

            .img-logo {
                margin-top: 10px;
            }



            body {
                display: flex;
                min-height: 100vh;
                flex-direction: column;
            }

            main {
                flex: 1 0 auto;
            }
        </style>

    </head>
        <div class="green navbar-fixed">
                <nav>
                    <ul id="dropdown2" class="dropdown-content">
                        {% for key, value in link.dropdown2.items %}
                        <li><a href="{{ value }}">{{ key }}</a></li>
                        {% endfor %}
                    </ul>
                    <ul id="dropdown1" class="dropdown-content">
                        {% for key, value in link.dropdown1.items %}
                        <li><a href="{{ value }}">{{ key }}</a></li>
                        {% endfor %}
                    </ul>
                <div class="green nav-wrapper">  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                 <ul class="left hide-on-med-and-down">
                     {% for key, value in link.links.items %}
                         <li><a href="{{ link.hyperlinks|key:key}}" class="dropdown-button" data-beloworigin="true" data-hover="true" data-constrainwidth="false"  data-activates="{{ value }}">{{ key }}</a></li>
                     {% endfor %}
                 </ul>
                  <ul id="mobile-demo" class="side-nav">
                    <li class="no-padding">
                      <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-teal">Dropdown 1</a>
                          <div class="collapsible-body">
                            <ul>
                              <li><a href="#">dowolny link</a></li>
                              <li><a href="#">dowolny link</a></li>
                              <li><a href="#">dowolny link</a></li>
                            </ul>
                          </div>
                        </li>
                        <li class="bold"><a class="collapsible-header waves-teal">Dropdown 2</a>
                          <div class="collapsible-body">
                            <ul>
                              <li><a href="#">dowolny link</a></li>
                              <li><a href="#">dowolny link</a></li>
                              <li><a href="#">dowolny link</a></li>
                            </ul>
                          </div>
                        </li>
                        <li class="bold"><a class="collapsible-header waves-teal">Dropdown 3</a>
                          <div class="collapsible-body">
                            <ul>
                              <li><a href="#">link1</a></li>
                              <li><a href="#">link2</a></li>
                              <li><a href="#">link3</a></li>
                            </ul>
                          </div>
                            </li>
                            <li class="bold"><a href="#" class="waves-teal">Normal link 1</a></li>
                            <li class="bold"><a href="#" class="waves-teal">Normal link 2</a></li>
                        </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

        <div class="center">
            <img src="{{ link.logo }}" class="img-logo img-responsive" >
            <hr>
        </div>



    {% block content %}

    {% endblock %}

    <footer class="page-footer green">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="white-text">Nasza szkoła!</h5>
                        <p class="grey-text text-lighten-4">{{ link.schoolName }}</p>
                    </div>

                    <div class="col l4 offset-l2 s12">
                        <h5 class="white-text">Polecane przez nas strony:</h5>

                        <ul>
                            {% for key, value in link.links_footer.items %}
                            <li><a class="grey-text text-lighten-3" href="{{ value }}">{{ key }}</a></li>

                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="footer-copyright green darken-1">
                <div class="container">
                    @ 2017 ZSAT-ROPCZYCE wszelkie prawa niezastrzeżone
                    <a class="grey-text text-lighten-4 right">{{ link.chief }}</a>
                </div>
            </div>
        </footer>

    <script>
        $(".button-collapse").sideNav();
    </script>

    </body>

</html>

school_website_template/templates/contact.html
{% extends "base.html" %}


    {% block content %}
    <main class="center">
        <h3 class="green-text">Twórcy projektu:</h3>
        <h4 class="green-text">Zespół szkół agro-technicznych im. Wincentego Witosa</h4>
    </main>
    {% endblock %}

school_website_template/templates/gallery/all_galleries.html
{% extends "base.html" %}
    {% block content %}
    <main class="center">
    <br/>
    <br/>
        {% for gallery in list_of_images %}
           {% for photo in gallery.image_in_gallery.all|slice:":1" %}
               <a href="{{ gallery.id }}">
                <img src="{{ photo.image.url }}">
                </div>
               </a>
           {% endfor %}
        {% endfor %}
    </main>
    {% endblock %}

school_website_template/templates/gallery/all_of_current_id.html
{% extends "base.html" %}

{% block content %}
    <main class="center">

        <style>
            img {
                max-width: 480px;
            }
        </style>

        {% for img in list_of_images %}
            <div>
                {{ img.title }}
                <br/><br/>
                <img class="img-responsive" src="{{ img.image.url }}"/>
                <br/>
            </div>

        {% endfor %}
    </main>
{% endblock %}

school_website_template/templates/gallery/gallery_form_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="../upload/" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="files" multiple/>
        <input type="submit" value="Dodaj"/>
    </form>
</body>
</html>

school_website_template/templates/gallery/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send" />
</form>
</body>
</html>

school_website_template/templates/main_page/main_page.html
{% extends "base.html" %}


    {% block content %}
    <main>
    <div class="container">
        {% for post in list_of_website_posts %}
            <div class="row">
                <img src="{{ post.image.url }}" align="left" class="img-post">
                <p>{{ post.content|safe }}</p>
            </div>
            <br/>
           <br/>
        {% endfor %}
    </div>
    </main>
    {% endblock %}


</html>

school_website_template/templates/website_post/create_website_post.html
{% load staticfiles %}
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Dodawanie wpisów na stronę</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


        <style type="text/css">

            body {
                background: url("media/bg2.jpg") no-repeat;
                background-size: 100% 100%;
            }

            html {
                height: 100%
            }
            .form-style-9{
                max-width: 900px;
                background: #FAFAFA;
                padding: 30px;
                margin: 50px auto;
                box-shadow: 2px 2px 25px rgba(0, 0, 0, 0.35);
                border-radius: 10px;
            }
            .form-style-9 ul{
                padding:0;
                margin:0;
                list-style:none;
            }
            .form-style-9 ul li{
                display: block;
                margin-bottom: 10px;
                min-height: 35px;
            }
            .form-style-9 ul li  .field-style {
                box-sizing: border-box;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                padding: 8px;
                outline: none;
                -webkit-transition: all 0.30s ease-in-out;
                -moz-transition: all 0.30s ease-in-out;
                -o-transition: all 0.30s ease-in-out;
            }

            .form-style-9 ul li  .field-style:focus{
                box-shadow: 0 0 5px #006600;
                border:1px solid #006600;
            }
            .form-style-9 ul li .field-split{
                width: 49%;
            }

            .form-style-9 ul li input.align-left{
                float:left;
            }
            .form-style-9 ul li input.align-right{
                float:right;
            }

            .btn-lg {
                background: #006600;
                color: white;
            }

            .btn-lg:hover {
                box-shadow: 0 0 5px #305A30;
                background: #006600;
                color: white;
            }

            .selectpicker {
                float:right;
                color: white;
            }

        </style>
    </head>

    <body>
        <div id="position">
            <form action="" method="post" enctype="multipart/form-data" class="form-style-9">
                {% csrf_token %}
                    <ul>
                        <li>
                            <input id="id_title" name="title" type="text" class="field-style field-split align-left" placeholder="Tytuł" />
                            <input id="id_author" name="author" type="text" class="field-style field-split align-right" placeholder="Autor" />
                        </li>

                        <li>
                            <div class="django-ckeditor-widget" data-field-id="id_content">
                                <textarea id="id_content" name="content" rows="10" cols="40"  data-processed="0" data-config='{"skin": "moono-lisa", "toolbar_Basic": [["Source", "-", "Bold", "Italic"]], "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline", "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"], ["Table", "HorizontalRule"], ["TextColor", "BGColor"], ["Smiley", "SpecialChar"], ["Source"]], "toolbar": "Full", "height": 291, "width": 838, "filebrowserWindowWidth": 940, "filebrowserWindowHeight": 725, "filebrowserUploadUrl": "/ckeditor/upload/", "filebrowserBrowseUrl": "/ckeditor/browse/", "language": "pl"}' data-external-plugin-resources='[]' data-id="id_content" data-type="ckeditortype" title="content_editor"></textarea>
                            </div>
                        </li>

                        <li>
                            <select id="id_category" name="category" title="Wybierz kategorię" class="selectpicker">
                                {% for value, text in form.fields.category.choices %}
                                        {% if forloop.counter != 1 %}
                                             <option value="{{ value }}">{{ text }}</option>
                                        {% endif %}
                                {% endfor %}
                            </select>

                            <input type="submit" value="Opublikuj" class="btn btn-lg align-right"/>
                        </li>

                        <li>
                        <input id="id_image" name="image" type="file" />
                        </li>
                    </ul>
            </form>
        </div>
    </body>
</html>